version: '3'

services:
  gui:
    build: ./gui
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./gui:/code
    ports:
      - "8000:8000"

  process:
    build: ./process
    command: python3 manage.py runserver 0.0.0.0:8001
    volumes:
      - ./process:/code
    ports:
      - "8001:8001"

  backend:
    build: ./backend
    command: python3 manage.py runserver 0.0.0.0:8002
    volumes:
      - ./backend:/code
    ports:
      - "8002:8002"
