apiVersion: v1
kind: Service
metadata:
  name: {{ include "django-process.fullname" . }}
spec:
  selector:
    app: {{ include "django-process.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
  type: {{ .Values.service.type }}

