apiVersion: v1
kind: Service
metadata:
  name: {{ include "django-backend.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ include "django-backend.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8002
  type: {{ .Values.service.type }}

                                                