name: Argo CD Sync
on:
  workflow_run:
    workflows: ["Docker Build and Deployment"]
    types:
      - completed

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Argo CD Action
        uses: argoproj/argocd-action@v2
        with:
          server: 192.168.49.2:31013
          username: ${{ secrets.ARGOCD_USERNAME }}
          password: ${{ secrets.ARGOCD_PASSWORD }}
          command: app sync
          args: |
            django-gui
            django-backend
