# Generated by Django 4.2.11 on 2024-04-18 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('simbolo', models.CharField(choices=[('IBM', 'IBM'), ('APPL', 'APPL'), ('TSLA', 'TSLA')], default='IBM', max_length=50)),
            ],
        ),
    ]
