# Generated by Django 4.2.11 on 2024-04-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0002_requestlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosFinancieros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('apertura', models.FloatField()),
                ('maximo', models.FloatField()),
                ('minimo', models.FloatField()),
                ('cierre', models.FloatField()),
                ('adj_close', models.FloatField()),
                ('volumen', models.IntegerField()),
            ],
        ),
    ]
